# canopen parameter
can_module: PCAN
can_baudrate: 500
max_accelerations: [0.8,0.8,0.8,0.8,0.8,0.8,0.8]
OperationMode: position

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 100 #68

joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
module_ids: [3,4,5,6,7,8,9]
devices: ["/dev/pcan2", "/dev/pcan2", "/dev/pcan2", "/dev/pcan2", "/dev/pcan2", "/dev/pcan2", "/dev/pcan2"]

#can_device: /dev/pcan2
#min_publish_duration: 0.1
#horizon: 0.1 # [s]
#force_use_movevel: True

